### ISSUE TITLE
Papyrus snippet for Game.ShowSPECIALMenu

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/Papyrus-Code#8]
The papyrus snippet for `Game.ShowSPECIALMenu` uses the wrong parameters.
It should be `Game.ShowSPECIALMenu()` but the snippet creates `Game.ShowSPECIALMenu(int aiPointPool, bool abStatsLocked)`.

**Comment by shad0wshayd3** [comment]
Fixed in e680cc9f515156298e2ae483fe8ee1dc771609bd.
